SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS application;
DROP TABLE IF EXISTS points_ledger;
DROP TABLE IF EXISTS user_warning;
SET FOREIGN_KEY_CHECKS=1;
